import { BusinessCategory, Company, ShoppingMall, Employee } from './types';

export const INITIAL_CATEGORIES: BusinessCategory[] = [
  {
    id: 'cat-realestate',
    name: 'Real Estate & Property',
    description: 'Management, construction, and operation of commercial shopping malls and office towers.',
    icon: 'Building2',
    color: 'emerald',
    riskLevel: 'Low',
  },
  {
    id: 'cat-retail',
    name: 'Retail Operations',
    description: 'Direct-to-consumer retail holdings, luxury brands, and anchor mall department stores.',
    icon: 'ShoppingBag',
    color: 'blue',
    riskLevel: 'Medium',
  },
  {
    id: 'cat-tech',
    name: 'Tech Ventures',
    description: 'Software solutions, AI research, cloud logistics, and corporate digital infrastructure.',
    icon: 'Cpu',
    color: 'indigo',
    riskLevel: 'High',
  },
  {
    id: 'cat-logistics',
    name: 'Logistics & Supply Chain',
    description: 'Global cargo forwarding, regional warehousing, and final-mile commercial delivery systems.',
    icon: 'Truck',
    color: 'amber',
    riskLevel: 'Medium',
  },
  {
    id: 'cat-hospitality',
    name: 'Hospitality & Leisure',
    description: 'Five-star hotel operations, premium resort development, and entertainment theaters.',
    icon: 'Coffee',
    color: 'rose',
    riskLevel: 'High',
  },
];

export const INITIAL_COMPANIES: Company[] = [
  {
    id: 'comp-estates',
    name: 'Masperv Estates Ltd.',
    categoryId: 'cat-realestate',
    foundedYear: 2008,
    budget: 68000000,
    status: 'Active',
    description: 'The foundation of the Masperv empire, managing premier commercial real estate and luxury retail malls nationwide.',
  },
  {
    id: 'comp-retail',
    name: 'Masperv Retail Group',
    categoryId: 'cat-retail',
    foundedYear: 2012,
    budget: 34000000,
    status: 'Active',
    description: 'Direct operators of department stores, high-end apparel chains, and premium electronics boutiques.',
  },
  {
    id: 'comp-digital',
    name: 'Masperv Digital Labs',
    categoryId: 'cat-tech',
    foundedYear: 2019,
    budget: 15500000,
    status: 'Active',
    description: 'Focuses on building SaaS for corporate asset management, ERP modules, and integration with modern machine learning.',
  },
  {
    id: 'comp-logistics',
    name: 'Masperv Logistics & Cargo',
    categoryId: 'cat-logistics',
    foundedYear: 2015,
    budget: 22000000,
    status: 'Restructuring',
    description: 'Supplies intermodal shipping services and manages heavy cargo networks linking manufacturing hubs with Masperv Malls.',
  },
  {
    id: 'comp-leisure',
    name: 'Masperv Leisure & Resorts',
    categoryId: 'cat-hospitality',
    foundedYear: 2014,
    budget: 18000000,
    status: 'Planning',
    description: 'Developing high-end hospitality complexes, luxury spas, and boutique entertainment theaters embedded in newer malls.',
  },
];

export const INITIAL_MALLS: ShoppingMall[] = [
  {
    id: 'mall-galleria',
    name: 'Masperv Galleria',
    location: 'Manhattan, New York',
    gla: 1250000,
    storesCount: 280,
    occupancyRate: 97.2,
    associatedCompanyId: 'comp-estates',
    annualFootfall: 24.5,
    description: 'Masperv\'s crown jewel property. High-traffic ultra-luxury center housing flagship fashion houses and dining halls.',
  },
  {
    id: 'mall-grandplaza',
    name: 'Masperv Grand Plaza',
    location: 'Beverly Hills, Los Angeles',
    gla: 920000,
    storesCount: 195,
    occupancyRate: 94.8,
    associatedCompanyId: 'comp-estates',
    annualFootfall: 18.2,
    description: 'A modern, open-air lifestyle retail destination catering to affluent demographics with extensive entertainment zones.',
  },
  {
    id: 'mall-crestwood',
    name: 'Masperv Crestwood Mall',
    location: 'Chicago, Illinois',
    gla: 780000,
    storesCount: 120,
    occupancyRate: 85.5,
    associatedCompanyId: 'comp-estates',
    annualFootfall: 11.4,
    description: 'A regional retail and office hybrid currently being restructured to include medical suites and a logistics dispatch center.',
  },
  {
    id: 'mall-pavilion',
    name: 'Masperv Bay Pavilion',
    location: 'Miami, Florida',
    gla: 1050000,
    storesCount: 215,
    occupancyRate: 91.0,
    associatedCompanyId: 'comp-estates',
    annualFootfall: 20.1,
    description: 'Waterfront commercial hub experiencing explosive traffic growth, featuring high-end resort boutiques and maritime recreation.',
  },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-001',
    name: 'Arthur Pendelton',
    email: 'a.pendelton@masperv-estates.com',
    phone: '+1 (555) 234-5678',
    role: 'VP of Commercial Properties',
    companyId: 'comp-estates',
    categoryId: 'cat-realestate',
    salary: 210000,
    status: 'Active',
  },
  {
    id: 'emp-002',
    name: 'Sarah Jenkins',
    email: 's.jenkins@masperv-estates.com',
    phone: '+1 (555) 345-6789',
    role: 'General Manager - Galleria Mall',
    companyId: 'comp-estates',
    mallId: 'mall-galleria',
    categoryId: 'cat-realestate',
    salary: 145000,
    status: 'Active',
  },
  {
    id: 'emp-003',
    name: 'David Kim',
    email: 'd.kim@masperv-retail.com',
    phone: '+1 (555) 456-7890',
    role: 'Chief Merchandising Officer',
    companyId: 'comp-retail',
    categoryId: 'cat-retail',
    salary: 185000,
    status: 'Active',
  },
  {
    id: 'emp-004',
    name: 'Elena Rostova',
    email: 'e.rostova@masperv-digital.com',
    phone: '+1 (555) 567-8901',
    role: 'Director of AI Engineering',
    companyId: 'comp-digital',
    categoryId: 'cat-tech',
    salary: 195000,
    status: 'Active',
  },
  {
    id: 'emp-005',
    name: 'Marcus Vance',
    email: 'm.vance@masperv-logistics.com',
    phone: '+1 (555) 678-9012',
    role: 'Chief Logistics Officer',
    companyId: 'comp-logistics',
    categoryId: 'cat-logistics',
    salary: 175000,
    status: 'Active',
  },
  {
    id: 'emp-006',
    name: 'Chloe Leblanc',
    email: 'c.leblanc@masperv-leisure.com',
    phone: '+1 (555) 789-0123',
    role: 'Head Resort Experience Architect',
    companyId: 'comp-leisure',
    categoryId: 'cat-hospitality',
    salary: 155000,
    status: 'Active',
  },
  {
    id: 'emp-007',
    name: 'Niels Borring',
    email: 'n.borring@masperv-digital.com',
    phone: '+1 (555) 890-1234',
    role: 'Senior Staff Full Stack Developer',
    companyId: 'comp-digital',
    categoryId: 'cat-tech',
    salary: 160000,
    status: 'Active',
  },
  {
    id: 'emp-008',
    name: 'Lydia Warren',
    email: 'l.warren@masperv-estates.com',
    phone: '+1 (555) 901-2345',
    role: 'Leasing Director - Grand Plaza',
    companyId: 'comp-estates',
    mallId: 'mall-grandplaza',
    categoryId: 'cat-realestate',
    salary: 120000,
    status: 'Active',
  },
  {
    id: 'emp-009',
    name: 'Rajesh Patel',
    email: 'r.patel@masperv-logistics.com',
    phone: '+1 (555) 012-3456',
    role: 'Fleet Distribution Manager',
    companyId: 'comp-logistics',
    categoryId: 'cat-logistics',
    salary: 95000,
    status: 'On Leave',
  },
  {
    id: 'emp-010',
    name: 'Amanda Zheng',
    email: 'a.zheng@masperv-retail.com',
    phone: '+1 (555) 123-4567',
    role: 'Regional Operations Supervisor',
    companyId: 'comp-retail',
    categoryId: 'cat-retail',
    salary: 115000,
    status: 'Active',
  },
  {
    id: 'emp-011',
    name: 'Julian Sterling',
    email: 'j.sterling@masperv-leisure.com',
    phone: '+1 (555) 321-7654',
    role: 'Hospitality Design Planner',
    companyId: 'comp-leisure',
    categoryId: 'cat-hospitality',
    salary: 130000,
    status: 'Contract',
  }
];
